// flow-typed signature: 303424851aa154ba74370fcf731c53a2
// flow-typed version: <<STUB>>/text-stream-accumulator_v1.1.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'text-stream-accumulator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'text-stream-accumulator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'text-stream-accumulator/dist/text-stream-accumulator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'text-stream-accumulator/dist/text-stream-accumulator.js' {
  declare module.exports: $Exports<'text-stream-accumulator/dist/text-stream-accumulator'>;
}
